name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    name: Lua Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bhupendraparihar/lua-typecheck-action@v1
        with:
          path: "lua/"

  tests:
    name: busted Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lunarmodules/nvim-busted-action@v1
        with:
          spec_path: "spec/"
